version: "3.9"

services:
  app:
    restart: "unless-stopped"
    build:
      context: .
    volumes:
      #- ./:/app
      - ./ruGPT-3.5-13B:/root/ruGPT-3.5-13B
      - ./cache:/root/.cache
      - ./output:/app/output
      - ./output_ggml:/app/output_ggml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
